### ISSUE TITLE
WIndows 11

### ISSUE THREAD

**Issue by xmha97** [knuth-konrad/winhlp32-on-windows10#1]
Hi, thanks for this help.
But it not working on Windows 11.
![image](https://github.com/knuth-konrad/winhlp32-on-windows10/assets/23485114/6d58acff-45c9-4820-b688-a8dae2a8d0c5)

**Comment by Wolf-SO** [comment]
@xmha97 Did you try to create the `expanded` directory before?

**Comment by xmha97** [comment]
> @xmha97 Did you try to create the `expanded` directory before?

No, this is my first time trying.

**Comment by Wolf-SO** [comment]
@xmha97 So do `mkdir expanded` first. BTW, this is what was explicitly stated in the step-by-step instructions:

> Create a (temporary) subfolder in the folder you created above, e.g. `expanded`.

In other words, the whole issue isn't valid. I'd suggest closing it (at least to correct the spelling in the summary).

**Comment by knuth-konrad** [comment]
Many thanks for helping out, @Wolf-SO. I seldom log in into Github, so this totally escaped me until today.
